In [1]:
%matplotlib inline
import datetime as dt
import numpy as np
import pandas as pd
import xarray as xr
import os
import time
import math
import gc
import matplotlib.pyplot as plt
import pylab

In [2]:
#load in netcdf file from which cdfs will be taken

direc = '/raid3/mbapt/pnw_surface_monitor/pnw/netcdf/'
file = "021916_historic_run_fluxes_.19790101-20151231.nc"
all_data = xr.open_dataset(os.path.join(direc,file))

In [3]:
#slice to the desired time period
#data_year = all_data.sel(time=slice('1981-1-1', '2010-12-31'))

#select out soil layer and then combine 
soil1 = all_data.sel(soil_layers=0)
soil2 = all_data.sel(soil_layers=1)
soil3 = all_data.sel(soil_layers=2)

allsoil = soil1['Soil_liquid'] + soil2['Soil_liquid'] + soil3['Soil_liquid']

In [4]:
#allsoil_lat = allsoil.sel(lat=44.03125) #44.03125 -117.78125
#allsoils = allsoil_lat.sel(lon=-117.78125)

In [10]:
#print(allsoil)

for g, data in allsoil.groupby('time.dayofyear'):
    print(g, data)

(1, <xarray.DataArray 'Soil_liquid' (time: 37, lat: 195, lon: 245)>
array([[[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        ..., 
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan]],

       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        ..., 
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan]],

       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        ..., 
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan,  nan

In [50]:
for label, data in allsoils.rolling(5, center=True, time=5):
    print(label, data)

(<xarray.DataArray 'time' ()>
numpy.datetime64('1979-01-01T00:00:00.000000000')
Coordinates:
    time         datetime64[ns] 1979-01-01
    lat          float64 44.03
    lon          float64 -117.8
    soil_layers  int64 2
Attributes:
    long_name: time, <xarray.DataArray (time: 1)>
array([ nan])
Coordinates:
  * time         (time) datetime64[ns] 1979-01-01
    lat          float64 44.03
    lon          float64 -117.8
    soil_layers  int64 2)
(<xarray.DataArray 'time' ()>
numpy.datetime64('1979-01-02T00:00:00.000000000')
Coordinates:
    time         datetime64[ns] 1979-01-02
    lat          float64 44.03
    lon          float64 -117.8
    soil_layers  int64 2
Attributes:
    long_name: time, <xarray.DataArray (time: 2)>
array([ nan,  nan])
Coordinates:
  * time         (time) datetime64[ns] 1979-01-01 1979-01-02
    lat          float64 44.03
    lon          float64 -117.8
    soil_layers  int64 2)
(<xarray.DataArray 'time' ()>
numpy.datetime64('1979-01-03T00:00:00.000000000')

KeyboardInterrupt: 

In [17]:
print(roll)

<xarray.DataArray (time: 10957)>
array([          nan,           nan,  288.43117731, ...,  229.63944321,
                 nan,           nan])
Coordinates:
    lat          float64 44.03
    lon          float64 -117.8
    soil_layers  int64 2
  * time         (time) datetime64[ns] 1981-01-01 1981-01-02 1981-01-03 ...


In [5]:
#slice to the desired time period
data_year = all_data.sel(time=slice('1981-1-1', '2010-12-31'))

#select out soil layer and then combine 
soil1 = all_data.sel(soil_layers=0)
soil2 = all_data.sel(soil_layers=1)
soil3 = all_data.sel(soil_layers=2)

allsoil = soil1['Soil_liquid'] + soil2['Soil_liquid'] + soil3['Soil_liquid']

'0.7.0'

In [ ]:
#read in list of grid cells for the PNW
coordinates = pd.read_csv('/raid3/mbapt/pnw_surface_monitor/pnw/historic_run_79-15/output/model_output/fluxes', sep='_', index_col=None, usecols=[1,2], delimiter=None, header=None)

latitude = coordinates[1]
longitude = coordinates[2]

In [ ]:
#create plotting positions using Wiebull distribution
q = []

for i in range(1,151):
    q.append(i/(150+1))

#iterate through each grid cell for soil liquid

In [ ]:
for i in range(0,20813):
    lat_data = all_soil.sel(lat=latitude[i])
    lon_data = lat_data.sel(lon=longitude[i])
    data_values = lon_data.values

    #set min and max values
    #data_max_a = max(data_values)
    #data_min_a = min(data_values)
    #data_max = math.ceil(data_max_a)
    #data_min = math.floor(data_min_a)
    
    #group by month and day
    s = pd.Series(data_values, index=pd.date_range('1981,1,1', '2010,12,31'))
    ss = s[(s.index.month!=2) | (s.index.day!=29)]
    gb = ss.groupby([ss.index.month, ss.index.day])
    
    
    for g, data in gb:
        #moving window of 5 days (kind of)
        current_day = dt.datetime(year=2011, month=g[0], day=g[1])
        yesterday = current_day - dt.timedelta(days=1)
        tomorrow = current_day + dt.timedelta(days=1)
        yesterday_2 = current_day - dt.timedelta(days=2)
        tomorrow_2 = current_day + dt.timedelta(days=2)
  
        cc = pd.concat([gb.get_group(g), gb.get_group((yesterday.month, yesterday.day)), gb.get_group((yesterday_2.month, yesterday_2.day)), gb.get_group((tomorrow.month, tomorrow.day)), gb.get_group((tomorrow_2.month, tomorrow_2.day))]) 
        cc.sort()

        month = current_day.strftime('%B')

        lat = latitude[i]
        lon = longitude[i]
        
        #plot option 
        #fig = plt.figure()
        #fig.suptitle('%s %s \n(1981-2010)' %(month, current_day.day), y=1.05, x=.5, fontsize=14, fontweight='bold')

        #ax = fig.add_subplot(111)
        #ax.set_xlabel('soil moisture \n(mm/day)')
        #ax.set_ylabel('percentile')

        #pylab.xlim([data_min, data_max])
    
        #datestring = (time.strftime("%c"))  

        #ax.text(data_min, -0.3, 'Created By: Marisa Baptiste')
        #ax.text(data_min, -0.35, datestring)
        #ax.text(data_min, -0.4, 'Lat: %s, Lon: %s' %(lat, lon))

        #plt.plot(cc, q)
        #plt.show() 

    
        plotname = '%s_%s' %(lat, lon)
        #path = ('/raid3/mbapt/ecflow/pnw/percentiles/soil_moist/plots/%s_%s' %(month, current_day.day))
        #if not os.path.exists(path):
        #    os.makedirs(path)
        #savepath = os.path.join(path, plotname)
        #plt.savefig(savepath, format='png', bbox_inches='tight')
    
        #save the 150 values by day
        path2 = ('/raid3/mbapt/ecflow/pnw/percentiles/soil_moist/textfiles/%s_%s' %(month, current_day.day))
        if not os.path.exists(path2):
            os.makedirs(path2)
        savepath2 = os.path.join(path2, plotname)
        cc.to_csv(savepath2, sep=' ', header=False, index=None)

In [ ]:
#save February 28 data as February 29
for i in range(0,20813):
    lat_data = all_soil.sel(lat=latitude[i])
    lon_data = lat_data.sel(lon=longitude[i])
    data_values = lon_data.values
    
    #set min and max values for plotting
    data_max_a = max(data_values)
    data_min_a = min(data_values)
    data_max = math.ceil(data_max_a)
    data_min = math.floor(data_min_a)

    #group by month and day
    s = pd.Series(data_values, index=pd.date_range('1981,1,1', '2010,12,31'))
    ss = s[(s.index.month!=2) | (s.index.day!=29)]
    gb = ss.groupby([ss.index.month, ss.index.day])


    g = (2,28)
    #moving window of 5 days (kind of)
    current_day = dt.datetime(year=2011, month=g[0], day=g[1])
    yesterday = current_day - dt.timedelta(days=1)
    tomorrow = current_day + dt.timedelta(days=1)
    yesterday_2 = current_day - dt.timedelta(days=2)
    tomorrow_2 = current_day + dt.timedelta(days=2)

    cc = pd.concat([gb.get_group(g), gb.get_group((yesterday.month, yesterday.day)), gb.get_group((yesterday_2.month, yesterday_2.day)), gb.get_group((tomorrow.month, tomorrow.day)), gb.get_group((tomorrow_2.month, tomorrow_2.day))])
    cc.sort()

    month = current_day.strftime('%B')

    lat = latitude[i]
    lon = longitude[i]
    
        #plot option
    #fig = plt.figure()
    #fig.suptitle('%s %s \n(1981-2010)' %(month, current_day.day), y=1.05, x=.5, fontsize=14, fontweight='bold')

    #ax = fig.add_subplot(111)
    #ax.set_xlabel('soil moisture (layer 1) \n(mm/day)')
    #ax.set_ylabel('percentile')

    #pylab.xlim([data_min, data_max])

    #datestring = (time.strftime("%c"))

    #ax.text(data_min, -0.3, 'Created By: Marisa Baptiste')
    #ax.text(data_min, -0.35, datestring)
    #ax.text(data_min, -0.4, 'Lat: %s, Lon: %s' %(lat, lon))

    #plt.plot(cc, q)
    #plt.show()


    plotname = '%s_%s' %(lat, lon)
    #path = ('/raid3/mbapt/ecflow/pnw/percentiles/soil_moist/plots/%s_%s' %(month, current_day.day))
    #if not os.path.exists(path):
    #    os.makedirs(path)
    #savepath = os.path.join(path, plotname)
    #plt.savefig(savepath, format='png', bbox_inches='tight')

    #save the 150 values by day
    path2 = ('/raid3/mbapt/ecflow/pnw/percentiles/soil_moist/textfiles/%s_%s' %(month, current_day.day))
    if not os.path.exists(path2):
        os.makedirs(path2)
    savepath2 = os.path.join(path2, plotname)
    cc.to_csv(savepath2, sep=' ', header=False, index=None)